id: P001747
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24106
  title: བློ་གཟང་དགོངས་རྒྱན་མུ་ཏིག་ཕྲེང་མཛེས་དེབ་སོ་བཞི་པ།
  author: ''
  volumes:
    57533b1bc9f8470c84d666530512a30f:
      image_group_id: I1KG24259
      title: ''
      volume_number: 1
      total_pages: 280
      base_file: v001.txt
