id: P001747
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG24106
  title: བློ་གཟང་དགོངས་རྒྱན་མུ་ཏིག་ཕྲེང་མཛེས་དེབ་སོ་བཞི་པ།
  author: ''
  volumes:
    57533b1bc9f8470c84d666530512a30f:
      image_group_id: I1KG24259
      title: ''
      volume_number: 1
      total_pages: 280
      base_file: v001.txt
